"""
batch_runner_pathb.py
Run Path B (master_pipeline_trial.py / FVNT native final stage) on the SAME
pairs that batch_runner.py used for Path A.

Always pass --pairs_file pointing to the eval_pairs.txt saved by batch_runner.py
so both paths process identical person-garment pairs.

Usage:
  conda run -n densepose python src/batch_runner_pathb.py \
      --dataset_root "D:/Final Project Viton/data" \
      --pairs_file   d:/VITON/outputs/eval_paired/eval_pairs.txt \
      --output_root  d:/VITON/outputs/eval_paired_pathb
"""

import argparse
import shutil
import subprocess
from pathlib import Path


def parse_args():
    p = argparse.ArgumentParser()
    p.add_argument("--dataset_root", default=r"D:/Final Project Viton/data")
    p.add_argument("--pairs_file",   required=True,
                   help="Path to eval_pairs.txt generated by batch_runner.py (Path A)")
    p.add_argument("--output_root",  default="d:/VITON/outputs/eval_paired_pathb")
    p.add_argument("--project_root", default="d:/VITON")
    p.add_argument("--conda_path",   default=r"C:/Users/hp/anaconda3/condabin/conda.bat")
    p.add_argument("--preprocess_env", default="densepose")
    p.add_argument("--parser_env",     default="densepose")
    p.add_argument("--pam_env",        default="fvnt_env")
    p.add_argument("--fvnt_env",       default="fvnt_env")
    p.add_argument("--pam_mode",       default="predict")
    p.add_argument("--skip_existing",  action="store_true")
    return p.parse_args()


def load_pairs(pairs_file: Path):
    """Returns list of (person_stem, cloth_stem) from eval_pairs.txt."""
    pairs = []
    with open(pairs_file) as f:
        for line in f:
            parts = line.strip().split()
            if len(parts) >= 2:
                pairs.append((Path(parts[0]).stem, Path(parts[1]).stem))
    return pairs


def run_one(person_stem: str, cloth_stem: str, dataset_root: Path,
            output_root: Path, args) -> bool:
    """Run master_pipeline_trial for one sample. Returns True on success."""
    person_path = dataset_root / "test" / "image" / f"{person_stem}.jpg"
    cloth_path  = dataset_root / "test" / "cloth"  / f"{cloth_stem}.jpg"
    sample_out  = output_root / person_stem

    # Path B final output lives at: sample_out/path_b/final/tryon_result_fvnt_native.png
    final_out = sample_out / "path_b" / "final" / "tryon_result_fvnt_native.png"
    if args.skip_existing and final_out.exists():
        print(f"  [skip] {person_stem} — output already exists")
        return True

    sample_out.mkdir(parents=True, exist_ok=True)

    cmd = [
        args.conda_path, "run", "--no-capture-output", "-n", args.preprocess_env,
        "python", str(Path(args.project_root) / "src" / "master_pipeline_trial.py"),
        "--person",         str(person_path),
        "--garment",        str(cloth_path),
        "--type",           "flat",
        "--project_root",   args.project_root,
        "--output_root",    str(sample_out),
        "--conda_path",     args.conda_path,
        "--preprocess_env", args.preprocess_env,
        "--parser_env",     args.parser_env,
        "--pam_env",        args.pam_env,
        "--fvnt_env",       args.fvnt_env,
        "--pam_mode",       args.pam_mode,
    ]

    print(f"\n[batch_pathb] Running sample: {person_stem}")
    result = subprocess.run(cmd, capture_output=False)
    if result.returncode != 0:
        print(f"  [ERROR] {person_stem} failed (exit {result.returncode})")
        return False
    return True


def main():
    args = parse_args()
    dataset_root = Path(args.dataset_root)
    output_root  = Path(args.output_root)
    output_root.mkdir(parents=True, exist_ok=True)

    pairs_file = Path(args.pairs_file)
    if not pairs_file.exists():
        print(f"[ERROR] pairs_file not found: {pairs_file}")
        print("  Run batch_runner.py (Path A) first to generate eval_pairs.txt")
        return

    pairs = load_pairs(pairs_file)
    print(f"[batch_pathb] Loaded {len(pairs)} pairs from {pairs_file}")

    # Copy pairs file and GT/parse to output_root for compute_metrics.py
    shutil.copy2(pairs_file, output_root / "eval_pairs.txt")

    gt_links_dir = output_root / "_gt"
    gt_links_dir.mkdir(exist_ok=True)
    parse_links_dir = output_root / "_parse"
    parse_links_dir.mkdir(exist_ok=True)

    for person_stem, _ in pairs:
        src_gt = dataset_root / "test" / "image" / f"{person_stem}.jpg"
        if src_gt.exists() and not (gt_links_dir / f"{person_stem}.jpg").exists():
            shutil.copy2(src_gt, gt_links_dir / f"{person_stem}.jpg")
        src_parse = dataset_root / "test" / "image-parse-v3" / f"{person_stem}.png"
        if src_parse.exists() and not (parse_links_dir / f"{person_stem}.png").exists():
            shutil.copy2(src_parse, parse_links_dir / f"{person_stem}.png")

    passed, failed = [], []
    for person_stem, cloth_stem in pairs:
        ok = run_one(person_stem, cloth_stem, dataset_root, output_root, args)
        (passed if ok else failed).append(person_stem)

    print(f"\n[batch_pathb] Done. {len(passed)}/{len(pairs)} succeeded.")
    if failed:
        print(f"  Failed: {failed}")
    print(f"\nNow compute metrics with:")
    print(f"  conda run -n densepose python src/compute_metrics.py \\")
    print(f"      --eval_root {output_root} \\")
    print(f"      --generated_subpath path_b/final/tryon_result_fvnt_native.png")


if __name__ == "__main__":
    main()
